name: rna-seq
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - alsa-lib=1.2.10=hd590300_0
  - bedtools=2.31.1=hf5e1c6e_0
  - binutils_impl_linux-64=2.40=hf600244_0
  - bowtie=1.3.1=py310h7b97f60_6
  - bowtie2=2.5.1=py310ha0a81b8_2
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bwa=0.7.17=he4a0461_11
  - bwidget=1.9.14=ha770c72_1
  - bx-python=0.10.0=py310h551a815_0
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.24.0=hd590300_0
  - ca-certificates=2023.11.17=hbcca054_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.16.0=py310h2fee648_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - coloredlogs=15.0.1=pyhd8ed1ab_3
  - colormath=3.0.0=py_2
  - contourpy=1.2.0=py310hd41b1e2_0
  - curl=7.87.0=h6312ad2_0
  - cutadapt=4.6=py310h4b81fae_1
  - cycler=0.12.1=pyhd8ed1ab_0
  - dnaio=1.2.0=py310h4b81fae_0
  - expat=2.5.0=hcb278e6_1
  - fastp=0.23.4=h5f740d0_0
  - fastqc=0.12.1=hdfd78af_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.47.0=py310h2372a71_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - future=0.18.3=pyhd8ed1ab_0
  - gcc_impl_linux-64=13.2.0=h338b0a0_3
  - gettext=0.21.1=h27087fc_0
  - gfortran_impl_linux-64=13.2.0=h76e1118_3
  - giflib=5.2.1=h0b41bf4_3
  - glib=2.78.1=hfc55251_0
  - glib-tools=2.78.1=hfc55251_0
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=13.2.0=h338b0a0_3
  - harfbuzz=6.0.0=h8e241bc_0
  - hisat2=2.2.1=hdbdd923_6
  - htslib=1.17=h6bc39ce_1
  - humanfriendly=10.0=pyhd8ed1ab_6
  - humanize=4.9.0=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - isa-l=2.30.0=hd590300_6
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h166bdaf_2
  - kernel-headers_linux-64=2.6.32=he073ed8_16
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py310hd41b1e2_1
  - krb5=1.20.1=hf9c8cef_0
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=20_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=20_linux64_openblas
  - libcups=2.3.3=h36d4200_3
  - libcurl=7.87.0=h6312ad2_0
  - libdeflate=1.13=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=13.2.0=ha9c7c90_103
  - libgcc-ng=13.2.0=h807b86a_3
  - libgfortran-ng=13.2.0=h69a702a_3
  - libgfortran5=13.2.0=ha4646dd_3
  - libglib=2.78.1=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_3
  - libhwloc=2.9.1=hd6dc26d_0
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=2.1.4=h166bdaf_0
  - liblapack=3.9.0=20_linux64_openblas
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libpng=1.6.39=h753d276_0
  - libsanitizer=13.2.0=h7e041cc_3
  - libsqlite=3.44.2=h2797004_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-devel_linux-64=13.2.0=ha9c7c90_103
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libtiff=4.4.0=h0e0dad5_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=hd590300_5
  - lzstring=1.0.4=py_1001
  - make=4.3=hd18ef5c_1
  - markdown=3.5.1=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py310h2372a71_1
  - matplotlib-base=3.8.2=py310h62c0568_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - multiqc=1.19=pyhdfd78af_0
  - munkres=1.0.7=py_1
  - mysql-connector-c=6.1.11=h6eb9d5d_1007
  - ncurses=6.4=h59595ed_2
  - networkx=3.2.1=pyhd8ed1ab_0
  - numpy=1.26.3=py310hb13e2d6_0
  - openjdk=11.0.1=h516909a_1016
  - openjpeg=2.5.0=h7d73246_1
  - openssl=1.1.1w=hd590300_0
  - packaging=23.2=pyhd8ed1ab_0
  - pango=1.50.14=hd33c08f_0
  - pbzip2=1.1.13=h1fcc475_2
  - pcre2=10.40=hc3806b6_0
  - perl=5.32.1=7_hd590300_perl5
  - pigz=2.8=h2797004_0
  - pillow=10.0.1=py310ha6cbd5a_0
  - pip=23.3.2=pyhd8ed1ab_0
  - pixman=0.42.2=h59595ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyaml-env=1.1.0=pyhd8ed1ab_0
  - pybigwig=0.3.18=py310h722e95c_2
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysam=0.21.0=py310hff46b53_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.8=h257c98d_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-isal=1.5.3=py310h2372a71_0
  - python_abi=3.10=4_cp310
  - pyyaml=5.4.1=py310h5764c6d_4
  - r-base=4.2.2=h6b4767f_2
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - rich=13.7.0=pyhd8ed1ab_0
  - rich-click=1.7.3=pyhd8ed1ab_0
  - rseqc=5.0.3=py310h4b81fae_0
  - samtools=1.18=hd87286a_0
  - sed=4.8=he412f7d_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - simplejson=3.19.2=py310h2372a71_0
  - six=1.16.0=pyh6c4a22f_0
  - spectra=0.0.11=py_1
  - star=2.7.11a=h0033a41_0
  - sysroot_linux-64=2.12=he073ed8_16
  - tbb=2021.9.0=hf52228f_0
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h0c5db8f_5
  - typing_extensions=4.9.0=pyha770c72_0
  - tzdata=2023d=h0c530f3_0
  - ucsc-genepredtobed=447=h954228d_0
  - unicodedata2=15.1.0=py310h2372a71_0
  - urllib3=2.1.0=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xopen=1.8.0=py310hff52083_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstandard=0.22.0=py310h1275a96_0
  - zstd=1.5.5=hfc55251_0
prefix: /mnt/nfs/users/pub/software/miniconda3/envs/rna-seq
